Repository sopt-makers/SOPT-iOS, pull requests merged in 2022-11, with the labels that each got.

#6 [Add] #5 - 폰트, 컬러, 이미지 에셋 추가
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/logo.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/logo.imageset/logo.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/logo.imageset/logo@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/logo.imageset/logo@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/error100.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/error500.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/error900.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/mint.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/pink.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/pink100.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/purple100.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/purple200.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/purple300.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Fonts/Montserrat-Bold.ttf
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Fonts/Montserrat-Regular.ttf
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Fonts/Pretendard-Bold.otf
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Fonts/Pretendard-Medium.otf
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Fonts/Pretendard-Regular.otf
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Font/UIFont+.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/UIFont+.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/setTypoStyle.swift
Labels: Add, 세진🥸

#10 [Setting] #9 - provisioning profile 세팅 수정
  SOPT-Stamp-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
Labels: Setting, size/XS

#11 [Feat] #4 - UI Component 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/error200.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/PointColor/error300.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Presentation/Sources/Components/CustomButton.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/Components/CustomTextFieldView.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/Components/TestVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/SceneDelegate.swift
Labels: Feat, 세진🥸, size/L

#16 [Feat] #15 - Tuist로 DemoApp 생성
  DependencyGraphs/AllGraph.png
  DependencyGraphs/AppGraph.png
  DependencyGraphs/TestGraph.png
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/.swiftlint.yml
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Project.swift
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Resources/Assets.xcassets/Contents.json
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Resources/Launch Screen.storyboard
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Sources/Application/AppDelegate.swift
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Sources/Application/SceneDelegate.swift
  SOPT-Stamp-iOS/Projects/Demo/SOPT-Stamp-Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Demo/Resources/Launch Screen.storyboard
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Demo/Sources/Application/AppDelegate.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Demo/Sources/Application/SceneDelegate.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Demo/Sources/Demo+/UIFont+.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Project.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-Stamp-iOS/Workspace.swift
Labels: Feat, 준호🍊, size/L

#18 [Fix] #17 - CustomNavigationBar 수정, typoStyle 추가
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icAddRecord.imageset/Add_record.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icAddRecord.imageset/Add_record@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icAddRecord.imageset/Add_record@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icAddRecord.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icArrow.imageset/Arrow.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icArrow.imageset/Arrow@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icArrow.imageset/Arrow@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icArrow.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icDelete.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icDelete.imageset/Delete.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icDelete.imageset/Delete@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icDelete.imageset/Delete@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomNavigationBar.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/UIFont+.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/AppDelegate.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: Fix, 양수💡, size/L

#21 [Feat] #8 - 스플래시, 앱아이콘 추가
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg1.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg1.imageset/splashImg1.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg1.imageset/splashImg1@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg1.imageset/splashImg1@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg2.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg2.imageset/splashImg2.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg2.imageset/splashImg2@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg2.imageset/splashImg2@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg3.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg3.imageset/splashImg3.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg3.imageset/splashImg3@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/splashImg3.imageset/splashImg3@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomButton.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomNavigationBar.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomTextFieldView.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/Components/TestVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/OnboardingScene/VC/OnboardingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SampleScene/VC/.gitkeep
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SampleScene/VC/SampleVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SampleScene/ViewModel/.gitkeep
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SampleScene/ViewModel/SampleViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/SplashVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/SceneDelegate.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 윤수🎁, size/L
