Repository sopt-makers/SOPT-iOS, pull requests merged in 2022-10, with the labels that each got.

#3 [Remove] 프로젝트 파일 삭제
  SOPT-iOS/SOPT-iOS.xcodeproj/project.pbxproj
  SOPT-iOS/SOPT-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SOPT-iOS/SOPT-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: Remove, 세진🍰, 윤수빙수✨, 양수빙수👾

#5 [Setting] #4 tuist적용
  .gitignore
  SOPT-iOS/.gitignore
  SOPT-iOS/Plugins/SOPTIOS/Package.swift
  SOPT-iOS/Plugins/SOPTIOS/Plugin.swift
  SOPT-iOS/Plugins/SOPTIOS/ProjectDescriptionHelpers/LocalHelper.swift
  SOPT-iOS/Plugins/SOPTIOS/Sources/tuist-my-cli/main.swift
  SOPT-iOS/Projects/Core/Project.swift
  SOPT-iOS/Projects/Core/Sources/Core.swift
  SOPT-iOS/Projects/Data/Project.swift
  SOPT-iOS/Projects/Data/Sources/Domain.swift
  SOPT-iOS/Projects/Domain/Project.swift
  SOPT-iOS/Projects/Domain/Sources/Domain.swift
  SOPT-iOS/Projects/Modules/Network/Project.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Network.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Sources/ThirdPartyLib.swift
  SOPT-iOS/Projects/Presentation/Project.swift
  SOPT-iOS/Projects/Presentation/Sources/Presentation.swift
  SOPT-iOS/Projects/SOPT-iOS/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/Contents.json
  SOPT-iOS/Projects/SOPT-iOS/Resources/Launch Screen.storyboard
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/SOPT-iOS/AppDelegate.swift
  SOPT-iOS/SOPT-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/SOPT-iOS/Base.lproj/LaunchScreen.storyboard
  SOPT-iOS/SOPT-iOS/Base.lproj/Main.storyboard
  SOPT-iOS/SOPT-iOS/Info.plist
  SOPT-iOS/SOPT-iOS/SceneDelegate.swift
  SOPT-iOS/SOPT-iOS/ViewController.swift
  SOPT-iOS/SOPT-iOSTests/SOPT_iOSTests.swift
  SOPT-iOS/SOPT-iOSUITests/SOPT_iOSUITests.swift
  SOPT-iOS/SOPT-iOSUITests/SOPT_iOSUITestsLaunchTests.swift
  SOPT-iOS/Tuist/Config.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-iOS/Workspace.swift
Labels: Setting, 세진🍰, 윤수빙수✨, 양수빙수👾

#8 [Setting] #6 Tuist SPM 세팅
  SOPT-iOS/Makefile
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  SOPT-iOS/Tuist/Dependencies.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Dependency-SPM.swift
Labels: Setting, 세진🍰, 윤수빙수✨, 양수빙수👾

#9 [Setting] SwiftLint적용
  SOPT-iOS/Projects/Presentation/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/.swiftlint.yml
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: Setting, 세진🍰, 윤수빙수✨, 양수빙수👾

#11 [FIx] #10 - infoPlist, SPM 수정
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Fix, 양수빙수👾

#13 [Feat] #12 - UtilityPlugin 추가
  SOPT-iOS/Plugins/SOPTIOS/Package.swift
  SOPT-iOS/Plugins/SOPTIOS/Plugin.swift
  SOPT-iOS/Plugins/SOPTIOS/ProjectDescriptionHelpers/LocalHelper.swift
  SOPT-iOS/Plugins/SOPTIOS/Sources/tuist-my-cli/main.swift
  SOPT-iOS/Plugins/UtilityPlugin/Plugin.swift
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Core/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Project.swift
  SOPT-iOS/Tuist/Config.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Setting, 양수빙수👾

#15 [Setting] #14 - 모듈 내부 폴더링
  SOPT-iOS/.gitignore
  SOPT-iOS/Projects/Core/Sources/Core.swift
  SOPT-iOS/Projects/Core/Sources/Extension/addPadding + UITextField.swift
  SOPT-iOS/Projects/Core/Sources/Literals/NotiList.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StoryboardLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Core/Sources/Protocols/UICollectionVIewRegisterable.swift
  SOPT-iOS/Projects/Core/Sources/Protocols/UITableViewRegisterable.swift
  SOPT-iOS/Projects/Core/Sources/Protocols/ViewModelType.swift
  SOPT-iOS/Projects/Core/Sources/Utils/addSubviews.swift
  SOPT-iOS/Projects/Core/Sources/Utils/getClassName.swift
  SOPT-iOS/Projects/Core/Sources/Utils/setTextLineHeight.swift
  SOPT-iOS/Projects/Data/Sources/Domain.swift
  SOPT-iOS/Projects/Data/Sources/Entity/Sample/SampleEntity.swift
  SOPT-iOS/Projects/Data/Sources/Repository/Sample/SampleRepository.swift
  SOPT-iOS/Projects/Domain/Sources/Domain.swift
  SOPT-iOS/Projects/Domain/Sources/Model/Sample/SampleModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/Sample/SampleRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Sample/SampleUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Network.swift
  SOPT-iOS/Projects/Modules/Network/Sources/ResponseObject.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/SampleService.swift
  SOPT-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-iOS/Projects/Presentation/Sources/Presentation.swift
  SOPT-iOS/Projects/Presentation/Sources/SampleScene/VC/SampleVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SampleScene/ViewModel/SampleViewModel.swift
  SOPT-iOS/Projects/Presentation/Sources/SampleScene/Views/Sample.storyboard
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/controllerFromStoryboard.swift
  SOPT-iOS/graph.png
Labels: Setting, 양수빙수👾

#19 [Feat] #16 - 게시글 상세보기 UI 구현
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/Result+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/String+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/URL+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIButton+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIColor+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIDevice+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIImage+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UILabel+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIStackView+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UISwitch+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UITabBar+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UITableView+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UITextField+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UITextView+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIView+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIViewController+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/addPadding + UITextField.swift
  SOPT-iOS/Projects/Core/Sources/Utils/Adjusted+.swift
  SOPT-iOS/Projects/Core/Sources/Utils/JsonCoder.swift
  SOPT-iOS/Projects/Core/Sources/Utils/ShowToast.swift
  SOPT-iOS/Projects/Core/Sources/Utils/UserDefaultWrapper.swift
  SOPT-iOS/Projects/Core/Sources/Utils/addToolBar.swift
  SOPT-iOS/Projects/Core/Sources/Utils/applyShadow.swift
  SOPT-iOS/Projects/Core/Sources/Utils/calculatePastTime.swift
  SOPT-iOS/Projects/Core/Sources/Utils/calculateTopInset.swift
  SOPT-iOS/Projects/Core/Sources/Utils/makeAlert.swift
  SOPT-iOS/Projects/Core/Sources/Utils/makeVibrate.swift
  SOPT-iOS/Projects/Core/Sources/Utils/setImage.swift
  SOPT-iOS/Projects/Core/Sources/Utils/setRootViewController.swift
  SOPT-iOS/Projects/Data/Sources/Entity/PostDetailEntity.swift
  SOPT-iOS/Projects/Data/Sources/Entity/Sample/SampleEntity.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PostDetailRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/Sample/SampleRepository.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PostDetailModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/Sample/SampleModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PostDetailRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/Sample/SampleRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PostDetailUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Sample/SampleUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/PostDetailService.swift
  SOPT-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/CollectionView/PostDetailCompositionalLayout.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/CollectionView/PostDetailSection.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/CollectionViewCell/PostDetailContentCVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/CollectionViewCell/PostDetailTitleCVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/CollectionViewCell/PostDetiailImagesCVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/VC/PostDetailVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/ViewModel/PostDetailViewModel.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 준호📱

#33 [Feat] #31 - 네트워크 모듈 구현
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Core/Sources/Extension/Combine+/AnyPublisher+.swift
  SOPT-iOS/Projects/Core/Sources/Utils/JsonCoder.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PostDetailRepository.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AlertAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/NoticeAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostDetailEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AFManager.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/ResponseObject.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AlertService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/NoticeService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/PostDetailService.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat

#36 [Feat] #35 - APNS 기본 세팅
  SOPT-iOS/Projects/SOPT-iOS/SOPT-iOS.entitlements
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
Labels: Feat, 윤수빙수✨, 양수빙수👾

#38 [Setting] #37 - Settings, info에 APNS 기본 세팅 추가
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Setting, 양수빙수👾

#43 [Setting] #42 - Network 레이어 수정, PostDetailTransform 추가
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PostDetailTransform.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostDetailEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AlertService.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Setting, 양수빙수👾

#47 [Feat] #46 - CustomNaviagtionBar
  SOPT-iOS/Projects/Presentation/Sources/Components/CustomNavigationBar.swift
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/VC/PostDetailVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/VC/PostListVC.swift
Labels: Feat, 양수빙수👾

#48 [Feat] #32 - 설정 뷰, 푸시 알림 설정 뷰 UI 구현
  SOPT-iOS/Projects/Data/Sources/Repository/PushAlarmSettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PushAlarmSettingTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PushAlarmSettingModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PushAlarmSettingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PushAlarmSettingUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PushAlarmSettingEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/PushAlarmSettingService.swift
  SOPT-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-iOS/Projects/Presentation/Sources/SampleScene/Views/Sample.storyboard
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/TVC/PushAlarmPartTVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/TVC/SettingTVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/VC/PushAlarmSettingVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/PushAlarmSettingViewModel.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/SettingViewModel.swift
  SOPT-iOS/Projects/SOPT-iOS/.gitkeep
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 윤수빙수✨

#45 [Feat] #44 - AWS SNS 세팅
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Plugins/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/Dependencies.swift
Labels: Feat, 양수빙수👾

#50 [Feat] #34 - Search UI 구현
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Protocols/UITableViewRegisterable.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PostListTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PostListModel.swift
  SOPT-iOS/Projects/Presentation/Sources/Components/CustomNavigationBar.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/VC/PostListVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/TableViewCell/PostListTableViewCell.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/TableViewCell/SearchHeaderView.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/ViewPager/ViewPager.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/graph.png
Labels: Feat, 양수빙수👾

#53 [Feat] #51 - 검색 Domain, Data 레이어 구현
  SOPT-iOS/Projects/Data/Sources/Repository/PostListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PostListTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PostSearchTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PostDetailModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PostListModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PushAlarmSettingModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PostDetailRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PostListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PushAlarmSettingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PostDetailUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PostListUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PushAlarmSettingUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostListEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostSearchEntity.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/VC/PostListVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/ViewModel/PostListViewModel.swift
Labels: Feat, 양수빙수👾

#62 [Setting] #61 - 세로모드, 라이트모드 고정
  SOPT-iOS/Projects/Presentation/Sources/PostDetailScene/VC/PostDetailVC.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Setting, 양수빙수👾

#59 [Feat] #58 - Push List 저장 기능 Domain 및 Data Layer 구현
  SOPT-iOS/Projects/Core/Sources/Extension/Combine+UIKit/CombineCompatible.swift
  SOPT-iOS/Projects/Core/Sources/Extension/Combine+UIKit/Publisher+UIControl.swift
  SOPT-iOS/Projects/Data/Sources/Repository/AuthPushAlarmRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AuthPushAlarmTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AuthPushAlarmModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/AuthPushAlarmRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AuthPushAlarmUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AlertAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/AuthPushAlarmEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AlertService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Presentation/Sources/AuthScene/VC/AuthPushAlarmVC.swift
  SOPT-iOS/Projects/Presentation/Sources/AuthScene/ViewModel/AuthPushAlarmViewModel.swift
  SOPT-iOS/Projects/Presentation/Sources/AuthScene/Views/TVC/AuthPushAlarmTVC.swift
  SOPT-iOS/Projects/Presentation/Sources/Components/CustomNavigationBar.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 준호📱

#60 [Feat] #56 - 푸시알림 세팅 뷰 Domain, Data, Network 레이어 연결
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PushAlarmSettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PushAlarmSettingTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PartCategory.swift
  SOPT-iOS/Projects/Domain/Sources/Model/Setting/PushAlarmSettingModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PushAlarmSettingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PushAlarmSettingUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AlertAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostSearchEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PushAlarmSettingEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AlertService.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/VC/PostListVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/TVC/PushAlarmPartTVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/VC/PushAlarmSettingVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/PushAlarmSettingViewModel.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
Labels: Feat, 양수빙수👾

#63 [Feat] #55 - 공지 리스트 뷰 Domain 및 Data Layer 기능 구현
  SOPT-iOS/Projects/Data/Sources/Repository/PostDetailRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PostListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PostListTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PartCategory.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PostListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PostListUseCase.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/NoticeAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PostListEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/NoticeService.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/VC/PostListVC.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/ViewModel/PostListViewModel.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/PostListPageView.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/TabItemView.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/ViewPager/CollectionView/TabbedView.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/ViewPager/CollectionViewCell/TabCollectionViewCell.swift
  SOPT-iOS/Projects/Presentation/Sources/PostListScene/Views/ViewPager/ViewPager.swift
Labels: Feat, 세진🤝🏻
