Repository sopt-makers/SOPT-iOS, pull requests merged in 2023-09, with the labels that each got.

#263 [Feat] #257 - 푸시 알림 서버 연결
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/String+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/NotificationDetailRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/NotificationListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SplashRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/MainTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/NotificationListTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/NotificationListModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/NotificationDetailRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/NotificationListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SplashRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/NotificationDetailUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/NotificationListUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SplashUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryCVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Views/MainNavigationBar.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Interface/Sources/NotifcationFeatureBuildable.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Interface/Sources/NotificationListPresentable.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/Coordinator/NotificationBuilder.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/Coordinator/NotificationCoordinator.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/VC/NotificationDetailVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/ViewModel/NotificationDetailViewModel.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/Cells/NotificationListCVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/VC/NotificationListVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/ViewModel/NotificationListViewModel.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashBuilder.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/ViewModel/SplashViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_active.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_active.imageset/Property 1=active.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_active.imageset/Property 1=active@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_active.imageset/Property 1=active@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_inactive.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_inactive.imageset/btn_notice.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_inactive.imageset/btn_notice@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_notice_inactive.imageset/btn_notice@3x.png
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/NotificationAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/MainEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/NotificationListEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseSessionDelegate.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/NotificationService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Feat, 세진🤝🏻, size/XL

#267 [Feat] DesignSystem Color 최신화, DEV 환경에서는 강제업데이트 하지 않도록 변경
  SOPT-iOS/Projects/Domain/Sources/UseCase/SplashUseCase.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/GrayScale/realWhite.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/Orange100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/legacy_red100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/System/Blue40.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/System/Blue50.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/System/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/System/Red100.colorset/Contents.json
Labels: Add, size/L

#272 [Chore] #269 - 로그인,팝업,알림뷰 보라색 제거
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVC.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVCTheme.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/VC/NotificationDetailVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/Cells/NotificationFilterCVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/VC/NotificationListVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/NoticePopUpVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/btn_check.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/btn_check@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/btn_check@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppCustomButton.swift
Labels: Chore, 세진🤝🏻, size/M

#277 [Improvement] 설정 하위 뷰에 있는 보라색 제거
  SOPT-iOS/Projects/Domain/Sources/UseCase/SplashUseCase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMyPageSubScenes/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppTextFieldView.swift
Labels: Chore, size/XS

#280 [Improvement] #270 - Unregistered inactive 제거
  SOPT-iOS/Projects/Core/Sources/Enum/UserType.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Domain/Sources/Error/MainError.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SignInUseCase.swift
  SOPT-iOS/Projects/Domain/Tests/Sources/UseCaseTests/MainUseCaseTests.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMyPageSubScenes/VC/PrivacyPolicyVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMyPageSubScenes/VC/TermsOfServiceVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMyPageSubScenes/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryHeaderView.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/ServiceTypeExtension.swift
Labels: size/L

#286 [Faet] #278 - 푸시 알림 스펙 변경 적용
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SplashRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/MainDescriptionTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/MainDescriptionModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SplashRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SplashUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/AppService/AppServiceHeaderView.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Features/MainFeature/Tests/Sources/MainViewModelTests/MainViewModelTests.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/VC/NotificationDetailVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/VC/NotificationListVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/ViewModel/NotificationListViewModel.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/ViewModel/SplashViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/DescriptionAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/MainDescriptionEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/DescriptionService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: Feat, 세진🤝🏻, size/L

#288 [Feat] 솝탬프 최근 기수인 경우 최근 기수에 맞추어 버튼, 랭킹리스트를 반환하도록 개선
  SOPT-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/RankingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/Rankingtransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/UsersActiveGenerationStateTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MissionListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/RankingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/Response/UsersActiveGenerationInfoViewResponse.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MissionListUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureBuildable.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/RankingCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampBuilder.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/RankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/ViewModel/RankingViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/RankAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/UsersActiveGenerationStatusEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/RankService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: Feat, size/L

#275 [Feat] #274 기능별 알림 추가
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/Codable+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Data/Sources/Repository/AppMyPageRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/NotificationSettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/NotificationSettingsTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/NotificationOptInModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/AppMyPageRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/NotificationSettingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AppMyPageUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/NotificationSettingByFeaturesUsecase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/AlertSettingByFeatures/NotificationSettingByFeaturesBuildable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/AlertSettingByFeatures/NotificationSettingByFeaturesPresentable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/MyPage/MyPageFeatureBuildable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/MyPage/MyPageFeatureControllables.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/MyPage/MyPagePresentable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/View/MyPageSectionListItemView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/View/MyPageViewSectionGroup.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/ViewModel/AppMyPageViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageSubScene/NotificationSettingByFeaturesScene/NotificationSettingByFeaturesVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageSubScene/NotificationSettingByFeaturesScene/View/NotificationSettingsListItemView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageSubScene/NotificationSettingByFeaturesScene/ViewModel/NotificationSettingByFeaturesViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/Coordinator/MyPageBuilder.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/Coordinator/MyPageCoordinator.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/NicknameEditVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/PrivacyPolicyVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/TermsOfServiceVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/ViewModel/NicknameEditViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/ViewModel/SentenceEditViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/ViewModel/SettingViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/ViewModel/WithdrawalViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/Views/SettingCVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/Views/SettingFooterView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/Views/SettingHeaderView.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/Orange100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppSwitchView.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppTextFieldView.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/GeneralNotificationOptInEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/NotificationOptInEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: Feat, size/XXL

#290 [Feat] #279 - Amplitude 적용
  SOPT-iOS/.gitignore
  SOPT-iOS/Makefile
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeInstance.swift
  SOPT-iOS/Projects/Core/Sources/Enum/AmplitudeEventType.swift
  SOPT-iOS/Projects/Core/Sources/Enum/ServiceTypeTransform.swift
  SOPT-iOS/Projects/Core/Sources/Enum/UserType.swift
  SOPT-iOS/Projects/Core/Sources/Utils/trackAmplitudeEvent.swift
  SOPT-iOS/Projects/Demo/Project.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/orange100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Project.swift
  SOPT-iOS/Tuist/Dependencies.swift
Labels: Feat, 세진🤝🏻, size/L

#292 [Fix] #289 SP0 QA 반영
  SOPT-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/CollectionView/MainViewCompositionalLayout.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/Frame 2606920.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/Frame 2606920@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/Frame 2606920@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo@3x.png
Labels: Fix, 세진🤝🏻, size/S

#293 [Chore] #291- 딤드 부분 임시로 주석 처리
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
Labels: Chore, 윤수🥚, size/XS

#295 [Fix] #294 푸시토큰 등록 버그 수정
  SOPT-iOS/Projects/Data/Sources/Repository/AppMyPageRepository.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/AppMyPageRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AppMyPageUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/ViewModel/AppMyPageViewModel.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/VC/NotificationListVC.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
Labels: Fix, 세진🤝🏻, size/M
