Repository sopt-makers/SOPT-iOS, pull requests merged in 2023-01, with the labels that each got.

#62 [Feat] #51 - ListDetail(스탬프 조회, 등록, 수정) Network 연결
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/ListDetailTransform.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/Model/ListDetailRequestModel.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/ListDetailRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/StampAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/ListDetailEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/StampService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/ViewModel/ListDetailViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/Cells/MissionListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/SplashVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/SceneDelegate.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 양수🌷, size/L

#67 [Fix] #66 - PHPickerViewController MainThread에서 돌아가도록 수정
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: Fix, 양수🌷, size/S

#65 [Feat] #61 - 스탬프 삭제, 초기화 Domain, Data 및 Network 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/ListDetailTransform.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/Model/ListDetailModel.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/SettingRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SettingUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/StampAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/StampService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/AlertScene/VC/AlertVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/ViewModel/ListDetailViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/SettingViewModel.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 양수🌷, size/L

#68 [Fix] #64 - postStamp 이후 ListDetailVC reloadData
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
Labels: Fix, 양수🌷, size/XS

#69 [Feat] #63 - 설정뷰 서비스 이용 방침 추가
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/PrivacyPolicyVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/TermsOfServiceVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 윤수☃️, size/L

#70 [Feat] #60 - 계정 찾기 뷰 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignInScene/VC/FindAccountVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignInScene/VC/SignInVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 윤수☃️, size/L

#73 [Feat] #72 - 랭킹 리스트 API 구현 및 1, 2, 3위 탭 액션 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Extension/Combine+/Publisher+Driver.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/RankingRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/Rankingtransform.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/SpeechBalloonView.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/RankAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/RankingEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/RankService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/Cells/RankingChartCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/Cells/RankingListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/Cells/RankingListTappable.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/VC/RankingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/ViewModel/RankingViewModel.swift
Labels: Feat, 준호🏅, size/L

#75 [Feat] #74 - 뷰윌어피어에서 미션 리스트 fetch하기
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
Labels: Feat, 준호🏅, size/M

#76 [Feat] #71 - 설정 뷰 로그아웃기능 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Utils/openExternalLink.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/PrivacyPolicyVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/TermsOfServiceVC.swift
Labels: Feat, 윤수☃️, size/M

#77 [Feat] #56 - 한 마디 편집 및 닉네임 변경 뷰 UI 및 기능 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/SettingTransform.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/SampleRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/SettingRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SampleUseCase.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SentenceEditUseCase.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SettingUseCase.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SignUpUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/RankAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/EditSentenceEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/RankService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/NicknameEditViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/SentenceEditViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/ViewModel/SignUpViewModel.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 준호🏅, size/XL

#79 [Fix] #78 - Network 모듈에 Domain 의존성 제거 및 userId 추가
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/ListDetailRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/StampAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/SampleEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/StampService.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
Labels: Fix, 양수🌷, size/M

#83 [Fix] #81 - 설정 뷰 1차 QA
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SettingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/ViewModel/SettingViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/Views/SettingFooterView.swift
Labels: Fix, 양수🌷, size/S

#84 [Fix] #80 - 1차 QA - 미션 리스트 및 랭킹 레이아웃 이슈, API 라우팅 수정, 스와이프 제스쳐 추가
  SOPT-Stamp-iOS/Projects/Core/Sources/Utils/setRootViewController.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/MissionListTransform.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/PaddingLabel.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/MissionListEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/MissionService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/Cells/MissionListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/VC/RankingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/SplashVC.swift
Labels: Fix, size/L

#89 [Fix] #87 - 회원가입 및 비밀번호 변경 뷰 1차 QA 반영
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/SignUpUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/PasswordSettingScene/VC/PasswordChangeVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/VC/SignUpCompleteVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/VC/SignUpVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/ViewModel/SignUpViewModel.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/SceneDelegate.swift
Labels: Fix, 세진🤝🏻, size/L

#85 [Fix] #82 - 글 수정, 상세 1차 QA
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomNavigationBar.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
Labels: Fix, 양수🌷, size/S

#91 [Fix] #86 - 랭킹에서 다른 사람 스탬프 상세 조회 연결, userId 분기처리
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/ListDetailRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomNavigationBar.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/ViewModel/ListDetailViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/Application/SceneDelegate.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Fix, 양수🌷, size/M

#97 [Fix] #96 - 회원가입뷰 비밀번호 경고 로직 수정
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomTextFieldView.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/ViewModel/SignUpViewModel.swift
Labels: Fix, 세진🤝🏻, size/S

#95 [Fix] #94 - 글 작성 하단 버튼 탭할 경우 바로 backgroundDimmerView 보이도록 수정
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/ListDetailRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionCompletedScene/VC/MissionCompletedVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Fix, 양수🌷, size/M

#99 [Fix] #98 - 내비바 및 미션리스트, 랭킹 자간 및 행간 수정 + 스탬프 크기 수정
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/ChartRectangleView.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomNavigationBar.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/SpeechBalloonView.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/RichString/String+ attributedString.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/Cells/MissionListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/Cells/RankingListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/VC/RankingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/PasswordSettingScene/VC/PasswordChangeVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SentenceEditVC.swift
Labels: Fix, size/M

#102 [Fix] #90 - 온보딩 뷰 1차 QA 반영
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/OnboardingScene/VC/OnboardingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/OnboardingScene/Views/CVC/OnboardingCVC.swift
Labels: Fix, 윤수☃️, size/M

#104 [Fix] #100 - 스탬프 등록, 삭제, 수정 실패시 에러 처리
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
Labels: Fix, 양수🌷, size/M

#106 [Fix/Feat] #88 - 한마디 디자인 변경, #101 - Tuist platForm 변경, #105 - 미션 리스트 엠티뷰 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/Model/RankingModel.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/missilnListEmpty.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/missilnListEmpty.imageset/missilnListEmpty.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/missilnListEmpty.imageset/missilnListEmpty@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/missilnListEmpty.imageset/missilnListEmpty@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/SpeechBalloonView.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListEmptyView.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/Cells/RankingListCVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/CollectionView/RankingCompositionalLayout.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/RankingScene/VC/RankingVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignInScene/VC/SignInVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignUpScene/VC/SignUpCompleteVC.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/Environment.swift
Labels: Feat, Fix, size/L

#110 [Fix] #109 - 스탬프 등록시 뒤에 이미지가 업로드 되는 모습이 보이지 않도록 수정
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
Labels: Fix, 양수🌷, size/XS

#112 [Fix] #111 - 로그인 화면전환 로딩 인디케이터 구현 및 릴리즈 전 마지막 수정작업
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/SignUpRepository.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomDimmerView.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomLoadingView.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/SignUpResponse.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SignInScene/VC/SignInVC.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-Stamp-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: Fix, size/L

#115 [Feat] #114 - 앱 강제 및 추천 업데이트 기능 구현
  SOPT-Stamp-iOS/Projects/Core/Sources/Extension/Foundation+/NSBundle+.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-Stamp-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Repository/AppNoticeRepository.swift
  SOPT-Stamp-iOS/Projects/Data/Sources/Transform/AppNoticeTransform.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/Model/AppNoticeModel.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/RepositoryInterface/AppNoticeRepositoryInterface.swift
  SOPT-Stamp-iOS/Projects/Domain/Sources/UseCase/AppNoticeUseCase.swift
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBox.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBox.imageset/checkBox.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBox.imageset/checkBox@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBox.imageset/checkBox@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBoxFill.imageset/Contents.json
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBoxFill.imageset/checkBoxFill.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBoxFill.imageset/checkBoxFill@2x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/icCheckBoxFill.imageset/checkBoxFill@3x.png
  SOPT-Stamp-iOS/Projects/Modules/DSKit/Sources/Components/CustomButton.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/API/FirebaseAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/AppNoticeEntity.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Entity/SignUpResponse.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-Stamp-iOS/Projects/Modules/Network/Sources/Service/FirebaseService.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/ModuleFactoryInterface.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/NoticePopUpVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/SplashVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/ViewModel/SplashViewModel.swift
  SOPT-Stamp-iOS/Projects/SOPT-Stamp-iOS/Sources/ModuleFactory/ModuleFactory.swift
Labels: Feat, 세진🤝🏻, size/XL

#118 [Fix] #117 - 공지 팝업 수정
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/NoticePopUpVC.swift
  SOPT-Stamp-iOS/Projects/Presentation/Sources/SplashScene/VC/SplashVC.swift
Labels: Fix, 세진🤝🏻, size/M

#120 [Fix] #119 - 미션 리스트가 empty일 경우 랭킹 버튼이 작동하지 않는 오류 수정
  SOPT-Stamp-iOS/Projects/Presentation/Sources/MissionListScene/VC/MissionListVC.swift
Labels: Fix, 준호🏅, size/XS
