Repository sopt-makers/SOPT-iOS, pull requests merged in 2023-04, with the labels that each got.

#142 [Refactor] #141 - 솝탬프 가이드 플로우 수정 및 랭킹 잘림 현상 해결
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Domain/Sources/Model/OnboardingDataModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/ServiceTypeExtension.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Features/OnboardingFeature/Demo/Resources/Launch Screen.storyboard
  SOPT-iOS/Projects/Features/OnboardingFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Interface/Sources/OnboardingFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Project.swift
  SOPT-iOS/Projects/Features/OnboardingFeature/Tests/Resources/dummy.txt
  SOPT-iOS/Projects/Features/OnboardingFeature/Tests/Sources/UnitTest.swift
  SOPT-iOS/Projects/Features/RootFeature/Project.swift
  SOPT-iOS/Projects/Features/SplashFeature/Project.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/SplashVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Example.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/Cells/RankingListCVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/StampGuideScene/VC/StampGuideVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/StampGuideScene/Views/CVC/StampGuideCVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/img_bottomLogo.imageset/img_bottomLogo@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/soptampLogo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/soptampLogo.imageset/logo.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/soptampLogo.imageset/logo@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/soptampLogo.imageset/logo@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/stampGuide.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/stampGuide.imageset/stampGuide.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/stampGuide.imageset/stampGuide@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/stampGuide.imageset/stampGuide@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/img_logo_Big.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/img_logo_Big.imageset/img_logo.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/img_logo_Big.imageset/img_logo@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/img_logo_Big.imageset/img_logo@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: size/L

#143 [Feat] #140 - 스플래시 및 로그인 UI
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Domain/Sources/Model/StampGuideDataModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/ViewModel/SignInViewModel.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVC.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertViewControllable.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/SplashVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/splashLogo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/splashLogo.imageset/splashLogo.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/splashLogo.imageset/splashLogo@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Splash/splashLogo.imageset/splashLogo@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STCustomButton.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: size/L

#145 [Refactor] #144 - 로그인 로직 구현 및 회원가입, 비밀번호 변경 레거시 삭제
  SOPT-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignUpRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PasswordSettingTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/SignInTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/SignUpTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PasswordChangeModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SignInRequest.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SignUpModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PasswordChangeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SignInRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SignUpRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PasswordChangeUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SignInUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SignUpUseCase.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/AuthFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/SignInModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/FindAccountVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/ViewModel/SignInViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/VC/SignUpCompleteVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/VC/SignUpVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/ViewModel/SignUpViewModel.swift
  SOPT-iOS/Projects/Features/SettingFeature/Interface/Sources/SettingFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/PasswordSettingScene/VC/PasswordChangeVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/PasswordSettingScene/ViewModel/PasswordChangeViewModel.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/SplashVC.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/PasswordChangeEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/SignInEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/SignUpEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/SignUpResponse.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: size/XXL

#148 [Refactor] #144 - UserID -> AccessToken 이전 작업 & API 변경사항 반영
  SOPT-iOS/Projects/Core/Sources/Enum/MissionListSceneType.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/RankingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignUpRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/RankDetailTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/Rankingtransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/RankingModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SignInModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/ListDetailRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MissionListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SignInRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MissionListUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainFeature.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Views/MainNavigationBar.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/ViewModel/ListDetailViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/Cells/RankingListCVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/Cells/RankingListTappable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/RankingVC.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/MissionAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/RankAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/StampAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/EditSentenceEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/ListDetailEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/MissionListEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/RankDetailEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/RankingEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/MissionService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/RankService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/StampService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: size/XL

#154 [Feat] #151 - 메인 뷰 및 팝업 뷰 UI수정
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVC.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVCTheme.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertViewControllable.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/MainService/BriefNoticeCVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryCVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryHeaderView.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/ServiceTypeExtension.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Views/MainNavigationBar.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/NoticePopUpVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/SplashVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_arrow_left.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_arrow_left.imageset/btn_arrow_left.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_arrow_left.imageset/btn_arrow_left@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_arrow_left.imageset/btn_arrow_left@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_active.imageset/Property 1=active@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_inactive.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_inactive.imageset/Property 1=inactive.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_inactive.imageset/Property 1=inactive@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_check_inactive.imageset/Property 1=inactive@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_logout.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_logout.imageset/btn_logout.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_logout.imageset/btn_logout@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Main/Btn/btn_logout.imageset/btn_logout@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/red100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Colors.xcassets/Main/PointColor/reddim100.colorset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Fonts/SUIT-Regular.otf
  SOPT-iOS/Projects/Modules/DSKit/Sources/UIFont+.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: Feat, 세진🤝🏻, size/L

#157 [Feat] #153- 출석 조회하기 API 연결
  SOPT-iOS/Projects/Core/Sources/Enum/AttendanceScheduleType.swift
  SOPT-iOS/Projects/Core/Sources/Enum/AttendanceStateType.swift
  SOPT-iOS/Projects/Data/Sources/Repository/ShowAttendanceRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceScheduleTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceScoreTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/ShowAttendanceTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceScheduleModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceScoreModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/ShowAttendanceModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/ShowAttendanceRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/MyAttendanceStateTVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/MyInformationWithScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/SingleScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/TodayScheduleView.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/OperationComponents/OPNavigationBar.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/AttendanceScheduleEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/AttendanceScoreEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/ShowAttendanceEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
Labels: Feat, 윤수🥚, size/XL

#162 [Feat] #150 - SOPTamp Dismiss 기능 추가
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icClose.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icClose.imageset/icClose.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icClose.imageset/icClose@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icClose.imageset/icClose@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
Labels: size/M

#163 [Feat] #160 - symbol 겹치는 이슈 해결
  DependencyGraphs/AllGraph.png
  DependencyGraphs/AppGraph.png
  DependencyGraphs/TestGraph.png
  SOPT-iOS/Projects/Core/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Core/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Core/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Core/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Data/Project.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/MainFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/MainFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/MainFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/MainFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/RootFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/RootFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/RootFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/RootFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/SettingFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/SettingFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/SettingFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/SettingFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/SplashFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/SplashFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/SplashFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/SplashFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Projects/Features/StampFeature/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Features/StampFeature/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/StampFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/StampFeature/Demo/Sources/ModuleFactory/ModuleFactory.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Fix, size/XXL, 영인☁️

#155 [Feat] #147 - MainView API 연결 및 탈퇴 API 수정
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/MainTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/MainModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/ServiceStateModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/ConfigAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/MainEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/ServiceStateEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AuthService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/ConfigService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: Feat, 세진🤝🏻, size/L

#166 [Feat] #149, #158 - 토큰 만료 로직, 플레이그라운드 로그인, 이외 여러 API 변경사항 반영
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-iOS/Projects/Core/Sources/Literals/URLContexts.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SettingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/Tests/Sources/UnitTest.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/AuthFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/StampAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/SignInEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/SoptampUserEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AFManager.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/APIEventLogger.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AlamoInterceptor.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate+HandleURL.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/SceneDelegate.swift
Labels: size/XL

#169 [Fix] #168 - 앱 아이콘 변경 및 스탬프 X버튼 수정
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.jpg
  SOPT-iOS/Projects/SOPT-iOS/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
Labels: size/XS

#172 [Feat] #167 - 출석 점수 조회하기 서버 수정
  SOPT-iOS/Projects/Data/Sources/Repository/ShowAttendanceRepository.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes@3x.png
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
Labels: Fix, size/L, 영인☁️

#175 [Feat] #174 - 메인 뷰 화면 연결
  SOPT-iOS/Projects/Core/Sources/Enum/ServiceType.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
Labels: Feat, size/M, 승호 🐶

#176 [Feat] #170 월 계산로직 수정 및 에러 핸들링
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/Date+.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
Labels: Feat, 세진🤝🏻, size/L

#180 [Feat] #178 - SFsafariViewController로 로그인 구현
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SafariServices/SFsafariViewController+.swift
Labels: size/M

#181 [Feat] #179 - UserType 핸들링
  SOPT-iOS/Projects/Core/Sources/Enum/UserType.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryCVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/Cells/UsersHistory/UserHistoryHeaderView.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
Labels: Feat, 세진🤝🏻, size/M

#190 [Chore] #187 - 1차 심사 전 출석조회 뷰 레이아웃 조정
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Core/Sources/Enum/AttendanceStateType.swift
  SOPT-iOS/Projects/Data/Sources/Repository/ShowAttendanceRepository.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/MyAttendanceStateTVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/MyInformationWithScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/SingleScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/TodayScheduleView.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/Cells/MissionListCVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/OperationComponents/OPNavigationBar.swift
Labels: Chore, 윤수🥚, size/L

#192 [Feat] #188 - 비활동 프로필 미등록 유저 프로젝트 및 마이페이지 분기
  SOPT-Stamp-iOS/SOPT-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Tuist/Dependencies.swift
Labels: size/M

#196 [Feat] #195 - 미등록 비활동 유저 회원탈퇴 처리
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/SettingFeature/Interface/Sources/SettingFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SettingVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/WithdrawalVC.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: size/M

#182 [Feat] #159 - 출석하기 UI 구현
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/String+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UIViewController+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Utils/addToolBar.swift
  SOPT-iOS/Projects/Data/Sources/Repository/AttendanceRepository.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/AttendanceRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Interface/Sources/AttendanceFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/Component/OPAttendanceCodeTextField.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/VC/AttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/View/AttendanceCodeView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/ViewModel/AttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/NicknameEditVC.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_close.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_close.imageset/Small.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_close.imageset/Small@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_close.imageset/Small@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/OperationComponents/OPCustomButton.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/UIFont+.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AttendanceAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Entity/AttendanceRoundEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseEntity.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: Feat, size/XL, 영인☁️

#198 [Feat] #183 - 출석하기 조회 UI 및 기능 구현
  SOPT-iOS/Projects/Core/Sources/Enum/AttendanceStepType.swift
  SOPT-iOS/Projects/Core/Sources/Enum/SessionType.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Utils/setDateFormat.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceScheduleTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceScheduleModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceStepModel.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/Component/OPAttendanceCodeTextField.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/VC/AttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/View/AttendanceCodeView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/ViewModel/AttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Component/OPAttendanceStepView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/TodayAttendanceView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/TodayScheduleView.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_done.imageset/Property 1=Done@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_late.imageset/Property 1=Late@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_no.imageset/Property 1=No@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Attendance/op_attend_yes.imageset/Property 1=Yes@3x.png
  SOPT-iOS/Projects/Modules/Network/Sources/MockData/AttendanceMockData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
Labels: Feat, size/XL, 영인☁️

#200 [Feat] #197 - 토큰 재발급 정상 작동하도록 수정 / 플그 미등록 비활동 유저 자동로그인 처리 / 스플래시 이미지 변경
  SOPT-iOS/Projects/Core/Sources/Enum/ServiceType.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SignInRepository.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/SplashVC.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/UserAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AFManager.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/APIError.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AlamoInterceptor.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
Labels: size/L

#194 [Setting] #189 - 테스트용 앱 환경 구축
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.jpg
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Application/SceneDelegate+HandleURL.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/ModuleFactory/DIContainer.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Setting, 세진🤝🏻, size/XL

#201 [Feat] #199 - 출석하기 API 연결 및 에러 대응
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Core/Sources/Enum/AttendanceErrorMsgType.swift
  SOPT-iOS/Projects/Core/Sources/Error/OPAPIError.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Core/Sources/Model/BaseEntity.swift
  SOPT-iOS/Projects/Data/Sources/Repository/AttendanceRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/ShowAttendanceRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceRoundTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceScheduleTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AttendanceScoreTransform.swift
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/ModuleFactory/DIContainer.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceRoundModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceScheduleModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/AttendanceRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/ShowAttendanceRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AttendanceUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Interface/Sources/AttendanceFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/VC/AttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/View/AttendanceCodeView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/ViewModel/AttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/AttendanceScoreComponents/MyInformationWithScoreView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Views/TodayScheduleView.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/AttendanceAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/MockData/AttendanceMockData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/AttendanceSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATAttendSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATLectureRoundSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATLectureSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATTotalSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: Feat, size/XXL, 영인☁️

#205 [Fix] 빌드 에러 및 무한로딩 에러 수정
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
Labels: Fix, size/XS

#206 [Feat] #202 - 1차 QA UI반영
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Features/SettingFeature/Sources/SettingScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/VC/NoticePopUpVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/StampGuideScene/VC/StampGuideVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
Labels: Feat, 세진🤝🏻, size/M

#212 [Feat] #204 - 출석 완료 상태 반영 및 에러 수정
  SOPT-iOS/Projects/Demo/SOPT-iOS-Demo/Sources/ModuleFactory/DIContainer.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Interface/Sources/AttendanceFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/VC/AttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/AttendanceScene/ViewModel/AttendanceViewModel.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/Component/OPAttendanceStepView.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATLectureSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/AttendanceService.swift
Labels: Feat, size/L, 영인☁️

#216 [Fix] #215 - SOPT-iOS 모듈의 DIContainer에 누락된 코드 추가
  SOPT-iOS/Projects/SOPT-iOS/Sources/ModuleFactory/DIContainer.swift
Labels: Fix, size/XS

#221 [Fix] #220 - 토큰 재발급 수정사항 반영
  SOPT-iOS/Projects/Modules/Network/Sources/API/AuthAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/AlamoInterceptor.swift
Labels: size/S
