Repository sopt-makers/SOPT-iOS, pull requests merged in 2023-05, with the labels that each got.

#224 [Feat] #223 - Sentry 세팅
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Demo/.swiftlint.yml
  SOPT-iOS/Projects/Demo/Project.swift
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.jpg
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/Contents.json
  SOPT-iOS/Projects/Demo/Resources/Launch Screen.storyboard
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/Application/SceneDelegate+HandleURL.swift
  SOPT-iOS/Projects/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/ModuleFactory/DIContainer.swift
  SOPT-iOS/Projects/Demo/Tests/Resources/dummy.txt
  SOPT-iOS/Projects/Demo/Tests/Sources/UnitTest.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/Dependencies.swift
Labels: size/M

#225 [Feat] #209 - 메인뷰 에러핸들링
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/MainTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Domain/Sources/Error/MainError.swift
  SOPT-iOS/Projects/Domain/Sources/Model/UserMainInfoModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/VC/MainVC.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/API/ConfigAPI.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Service/UserService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
Labels: Feat, 세진🤝🏻, size/L

#228 [Fix] #227 - Sentry 설정 변경 및 dsym 파일 업로드 script 추가
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: 준호🏅, size/M

#230 [Fix] #229 - URL State 생성 방식 UUID로 수정, Sentry 캡쳐
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
Labels: size/S

#233 [Fix] #232 - 출석하기 버튼 안보이는 에러 해결
  SOPT-iOS/Projects/Core/Sources/Utils/setDateFormat.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/AttendanceSampleData.swift
  SOPT-iOS/Projects/Modules/Network/Sources/SampleData/Attendance/Data/ATLectureSampleData.swift
Labels: Fix, size/M, 영인☁️

#237 [Feat] #236 - Sentry Capture 코드 추가
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Domain/Sources/Error/MainError.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Modules/Network/Sources/Foundation/BaseService.swift
Labels: Feat, 세진🤝🏻, size/M

#238 [Feat] #235 - fastlane 도입
  SOPT-iOS/.gitignore
  SOPT-iOS/Gemfile
  SOPT-iOS/fastlane/Appfile
  SOPT-iOS/fastlane/Fastfile
  SOPT-iOS/fastlane/Matchfile
  SOPT-iOS/fastlane/Pluginfile
  SOPT-iOS/fastlane/README.md
Labels: Feat, 세진🤝🏻, size/L

#240 [Add] #239 - FireBase 의존성 추가
  SOPT-iOS/.gitignore
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Demo/Project.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/Dependencies.swift
Labels: size/S
