Repository sopt-makers/SOPT-iOS, pull requests merged in 2024-10, with the labels that each got.

#397 [Fix] #395 - 딥링크 변경 사항 반영 및 baseURL trailing slash 수정
  SOPT-iOS/Projects/Core/Sources/Utils/setDateFormat.swift
  SOPT-iOS/Projects/Demo/Sources/AppLifecycleAdapter/AppLifecycleAdapter.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/DailySoptuneUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/NotificationDetailUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/NotificationListUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMessageTemplateUsecase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMyFriendsUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeOnboardingUsecase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/ViewModel/AppMyPageViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageSubScene/NotificationSettingByFeaturesScene/NotificationSettingByFeaturesVC.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/VC/ShowAttendanceVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DeepLinks/DailySoptuneWordDeepLink.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneCardVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneMainVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneCardViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneMainViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/VC/NotificationDetailVC.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/ViewModel/NotificationDetailViewModel.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/ViewModel/NotificationListViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMessageTemplatesScene/PokeMessageTemplateViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsListScene/ViewModel/PokeMyFriendsListViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/DeepLinks/DailySoptuneDeepLink.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/DeepLinks/HomeDeepLink.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/AppLifecycleAdapter/AppLifecycleAdapter.swift
Labels: Fix, size/L, 윤서🍉

#398 [Fix] #396 - 솝마디 결과뷰 컴포넌트 수정
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/String+.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneResultPresentable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Components/DailySoptuneProfileImageView.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneCardVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultContentView.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultPokeView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeNotificationListContentView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileCardView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileImageView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileListView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeAnonymousFriendUpgradeVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/CustomProfileImageView.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/PokeComponents/PKokButton.swift
Labels: Fix, size/L, 재현✦

#403 [Feat] #400 - 솝탬프 신고 기능 및 네트워크 오류 모달 추가
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/String+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/MissionListTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SoptampReportUrlModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MissionListUseCase.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Alert/AlertVCTheme.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Components/DailySoptuneProfileImageView.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultPokeView.swift
  SOPT-iOS/Projects/Features/MainFeature/Sources/MainScene/ViewModel/MainViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icReport.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Soptamp/icReport.imageset/ic_report.svg
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/StampAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/SoptampReportUrlEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/StampService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: Feat, size/L, 재현✦

#404 [Feat] #402 - 솝마디 앰플리튜드 이벤트 추가
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeEventType.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneCardVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneMainVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneCardViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneMainViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
Labels: Feat, size/M, 윤서🍉

#406 [Fix] #405 - import된 PokeFeatureInterface 삭제
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneFeatureBuildable.swift
Labels: Fix, size/XS, 재현✦

#411 [Fix] #409 - 스프린트0 QA
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
Labels: Fix, size/S, 재현✦

#412 [Fix] #410 - SE기기대응, 솝마디 토스트 메세지 추가
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneCardVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneMainVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultContentView.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultPokeView.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/ViewModel/NotificationDetailViewModel.swift
Labels: size/L

#415 [Fix] #414 - 누락된 토스트 메세지 추가
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/ViewModel/NotificationDetailViewModel.swift
Labels: size/XS

#419 [Feat] #407 - 로그인 뷰 UI 구현
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/AuthFeature/Demo/Sources/StubSignInRepository.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/AuthFeatureBuildable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/LoginHelpBottomSheetPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/SignInPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/UserNotFoundBuildable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/Coordinator/AuthBuilder.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/LoginHelpBottomSheetVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/SignInVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/VC/UserNotFoundVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/ViewModel/SignInViewModel.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/BottomSheetManager/BottomSheetConfiguration.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/BottomSheetManager/BottomSheetManager.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/alert-circle.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/alert-circle.imageset/alert-circle.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/alert-circle.imageset/alert-circle@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/alert-circle.imageset/alert-circle@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/exclamation-question-mark.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/exclamation-question-mark.imageset/Frame 1171275386@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/exclamation-question-mark.imageset/Frame 1171275386@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/exclamation-question-mark.imageset/exclamation-question-mark.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_apple.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_apple.imageset/Logo Apple@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_apple.imageset/Logo Apple@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_apple.imageset/logo_apple.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_google.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_google.imageset/Logo Google.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_google.imageset/Logo Google@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/SignIn/logo_google.imageset/Logo Google@3x.png
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppImageTextButton.swift
Labels: size/XL

#424 [Fix] #423 - 오탈자 수정
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/Coordinator/AuthCoordinator.swift
Labels: Fix, size/XS

#427 [Fix] #426 - Kingfisher 버전 업데이트
  SOPT-iOS/Tuist/Dependencies.swift
  SOPT-iOS/package.json
Labels: Fix, size/XS, 재현✦
