Repository sopt-makers/SOPT-iOS, pull requests merged in 2024-06, with the labels that each got.

#371 [Feature] 모델, 네트워크 변경점 반영
  SOPT-iOS/Projects/Data/Sources/Repository/PokeOnboardingRepository.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PokeRandomUserType.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PokeOnboardingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeOnboardingUsecase.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/PokeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/PokeUserEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/PokeService.swift
Labels: Feat, size/L, 승호 🐶

#372 [Feat] 콕 찌르기 개편
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PokeMainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PokeFriendRandomUserTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PokeUserTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PokeFriendRandomUserModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PokeUserModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PokeMainRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMainUseCase.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeAnonymousFriendUpgradePresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeFeatureBuildable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMainPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMyFriendsListPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMyFriendsPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeNotificationPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeNotificationListContentView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileCardView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileListView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeBuilder.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeMyFriendsCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeNotificationListCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/VC/PokeMainVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/ViewModel/PokeMainViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/Views/ProfileCardGroupView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeAnonymousFriendUpgradeVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsListScene/ViewModel/PokeMyFriendsListViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsScene/ViewModel/PokeMyFriendsViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeNotificationScene/ViewModel/PokeNotificationViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Lotties/bestFriend.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Lotties/soulmate.json
  SOPT-iOS/Projects/Modules/Networks/Sources/API/PokeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/PokeFriendRandomUserEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/PokeService.swift
Labels: Feat, size/XXL

#373 [Improvement] MDS Font Util 생성 및 Poke에 일부 적용
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeBottomSheetMessageView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeEmptyView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileCardView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Components/PokeProfileListView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/VC/PokeMainVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/Views/PokeMainSectionHeaderView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/Views/ProfileCardGroupView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeAnonymousFriendUpgradeVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeMakingFriendCompletedVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsScene/VC/PokeMyFriendsVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsScene/Views/PokeFriendsSectionHeaderView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeNotificationScene/PokeNotificationViewController.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/PokeOnboardingBottomSheet/PokeOnboardingBottomSheet.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Components/STPartChartRectangleView.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/MDS/MDSFont+Extension.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/MDS/MDSToast.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/UIFont+.swift
Labels: Feat, size/XL

#375 [Feature] PokeService 익명 바텀싯 적용, 모두 anonymous option 가지도록 수정
  SOPT-iOS/Projects/Data/Sources/Repository/PokeMainRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PokeMyFriendsRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PokeNotificationRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/PokeOnboardingRepository.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/PokeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMainUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeMyFriendsUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeNotificationUsecase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/PokeOnboardingUsecase.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMainPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMyFriendsListPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeMyFriendsPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeNotificationPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeOnboardingPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeMyFriendsCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeNotificationListCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeOnboardingCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/ViewModel/PokeMainViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMessageTemplatesScene/PokeMessageTemplateBottomSheet.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsListScene/ViewModel/PokeMyFriendsListViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsScene/ViewModel/PokeMyFriendsViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeNotificationScene/ViewModel/PokeNotificationViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/PokeOnboardingViewController.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/ViewModel/PokeOnboardingViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/MDS/check.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/MDS/check.imageset/check.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/MDS/check.imageset/check@2x.png
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/MDS/check.imageset/check@3x.png
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/PokeService.swift
Labels: Feat, size/XL, 승호 🐶

#377 [Improvement] 구글 폼 링크 -> 카카오톡 플친 링크로 수정
  SOPT-iOS/Projects/Core/Sources/Literals/ExternalURL.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageViewController.swift
Labels: Chore, size/XS, 승호 🐶

#379 [Fix] 자잘한 버그들 수정
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeMakingFriendCompletedVC.swift
Labels: size/XS

#380 [Improvement] Poke QA 2차
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/BottomSheetManager/BottomSheetConfiguration.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeMyFriendsCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeNotificationListCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeOnboardingCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMakingFriendCompletedScene/VC/PokeMakingFriendCompletedVC.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMessageTemplatesScene/PokeMessageTemplateBottomSheet.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/FlowLayout/PokeCarouselFlowLayout.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/PokeOnboardingBottomSheet/PokeOnboardingBottomSheet.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/PokeOnboardingViewController.swift
Labels: bug, size/L, 승호 🐶
