Repository sopt-makers/SOPT-iOS, pull requests merged in 2024-04, with the labels that each got.

#362 [Fix] #361 - 타이머 실행 전 출석하기 진입시 무한로딩 이슈 해결
  SOPT-iOS/Projects/Domain/Sources/Model/AttendanceRoundModel.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
Labels: Fix, size/XS, 민재 🦁

#364 [Fix] #363 - 무한로딩 해결 로직 수정
  SOPT-iOS/Projects/Data/Sources/Repository/ShowAttendanceRepository.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ShowAttendanceUseCase.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
Labels: Fix, size/S, 민재 🦁

#365 [Feat] #360 - 솝탬프 개선
  SOPT-iOS/Projects/Data/Sources/Repository/RankingRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/PartRankingTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PartRankingModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/RankingRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/RankingUseCase.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/Part.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureBuildable.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Components/STPartChartRectangleView.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/RankingCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampBuilder.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/Cells/PartRankingChartCVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/Cells/PartRankingListCVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/CollectionView/PartRankingCompositionalLayout.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/PartRankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/RankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/ViewModel/PartRankingViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/ViewModel/RankingViewModel.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/RankAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/PartRankingEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/RankService.swift
Labels: Feat, 세진🤝🏻, size/XXL

#367 [Fix] StampAPI에서 Domain import를 제거 - Transform 적용
  SOPT-iOS/Projects/Data/Sources/Repository/ListDetailRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/ListDetailTransform.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/StampAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ListDetailRequestEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/StampService.swift
Labels: Fix, size/M, 승호 🐶

#369 [Fix] Stamp 이슈 수정
  SOPT-iOS/Projects/Data/Sources/Repository/MissionListRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/SoptampUserTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/RankingModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SoptampUserModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/MissionListRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/MissionListUseCase.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/ViewModel/MissionListViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/RankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/ViewModel/RankingViewModel.swift
Labels: bug, size/XL, 승호 🐶
