Repository sopt-makers/SOPT-iOS, pull requests merged in 2025-03, with the labels that each got.

#510 [Fix] #507 - 솝탬프 메모리 최적화
  SOPT-iOS/Projects/Core/Sources/Utils/setImage.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/ListDetailUseCase.swift
  SOPT-iOS/Projects/Features/StampFeature/Interface/Sources/StampFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/MissionDetailCoordinator.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampBuilder.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/VC/ListDetailVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/PartRankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/RankingScene/VC/RankingVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/StampGuideScene/VC/StampGuideVC.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/SoptampComponents/STNavigationBar.swift
Labels: Fix, size/L, 재현✦

#462 [Feat] #408 - Amplitude 설치
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeEventType.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/Coordinator/NotificationCoordinator.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationDetailScene/ViewModel/NotificationDetailViewModel.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/NotificationListScene/ViewModel/NotificationListViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/NotificationHelpers/NotificationHandler.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/NotificationHelpers/NotificationPayload.swift
Labels: Feat, size/M, 승찬🧩

#512 [Fix] #511 - 솝트로그 화면 전환 수정 및 메모리 최적화
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneCardCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/Views/DailySoptuneResultPokeView.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
Labels: Fix, size/M, 재현✦

#518 [Fix] #517 - TabbarFeature 모듈 의존성 구조 변경
  SOPT-iOS/Projects/Features/RootFeature/Project.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Project.swift
Labels: Fix, size/S, 재현✦

#519 [Feat] #513 - 신규 홈뷰 Amplitude 이벤트 추가 및 화면전환 오류 해결
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeEventType.swift
  SOPT-iOS/Projects/Core/Sources/Enum/ServiceTypeTransform.swift
  SOPT-iOS/Projects/Core/Sources/Enum/TabBarItemType.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/MainProduct/MainProductCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForVisitorItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForVisitorViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/ServiceTypeExtension.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/NotificationHelpers/NotificationHandler.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Interface/Sources/SoptlogPresentable.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/Coordinator/SoptlogCoordinator.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/VC/SoptlogVC.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/ViewModel/SoptlogViewModel.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/StampGuideScene/VC/StampGuideVC.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/Components/TabBarItem.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/Controller/TabBarController.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/ViewModel/TabBarViewModel.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_group_logo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_group_logo.imageset/Frame 1171275665-1.svg
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_review_logo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_review_logo.imageset/Frame 1171275665.svg
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_user_logo.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_user_logo.imageset/img_user_logo.svg
Labels: Feat, Fix, size/L, 윤서🍉
