Repository sopt-makers/SOPT-iOS, pull requests merged in 2025-06, with the labels that each got.

#593 [Feat] #571 - 설문 폼 섹션, 소셜 링크 섹션 구현
  SOPT-iOS/Projects/Data/Sources/Repository/HomeRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomeSurveyTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomeSurveyModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/HomeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/HomeUseCase.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForMemberPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/SocialLinks/SocialLinkCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Survey/SurveyCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForMemberCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForMemberItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeItemRegistrationTypes.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/SectionLayoutKind/HomeForMemberSectionLayoutKind.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/LegacyHomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/ServiceTypeExtension.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Views/HomeDefaultHeaderView.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_girl_survey.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/Home/Image/img_girl_survey.imageset/img_girl_survey.svg
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/AppComponents/AppCustomButton.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/HomeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeCalendarDetailResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeDescriptionEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomePlaygroundNewsPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeSurveyResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/HomeService.swift
Labels: Feat, size/XL, 재현✦

#594 [Fix] #592 - 솝탬프 특별미션 UI 수정
  SOPT-iOS/Projects/Features/StampFeature/Sources/Components/STStarView.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/ListDetailScene/View/MissionView.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/Cells/MissionListCVC.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/Cells/MissionListCellType.swift
Labels: Fix, size/L, 윤서🍉

#596 [Hotfix] #595 - 런치 스크린 설정 방식 변경
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
Labels: Fix, size/XS, 재현✦

#603 [Refactor] #601 - MyPage UI 리팩토링
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/AppMyPageUseCase.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/MyPage/MyPageFeatureBuildable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Interface/Sources/MyPage/MyPagePresentable.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/AppMyPageVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/Cells/MyPageCVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/Cells/MyPageSectionBackgroundView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/Cells/MyPageSectionHeaderView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/CollectionView/CompositionalLayout/MyPageCompositionalLayout.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/CollectionView/Item/MyPageItem.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/CollectionView/Registration/MyPageItemProvider.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/CollectionView/Registration/MyPageItemRegistrationTypes.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/CollectionView/SectionLayoutKind/MyPageSectionLayoutKind.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/View/MyPageSectionListItemView.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/View/MyPageViewSectionGroup.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/AppMypageScene/ViewModel/AppMyPageViewModel.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/Coordinator/MyPageBuilder.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/Coordinator/MyPageCoordinator.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/SentenceEditVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/VC/TermsOfServiceVC.swift
  SOPT-iOS/Projects/Features/AppMyPageFeature/Sources/SOPTampScene/ViewModel/SettingViewModel.swift
Labels: Del, Refactor, size/XXL, 윤서🍉

#613 [Hotfix] #611 - 홈화면 버그 수정
  SOPT-iOS/Projects/Features/HomeFeature/Sources/CalendarDetailScene/VC/HomeCalendarDetailVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Calendar/CalendarCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Survey/SurveyCVC.swift
Labels: Fix, size/S, 재현✦

#614 [Feat] #525 - 계정 찾기 구현
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/Repository/CoreAuthRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/CoreOAuthRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/CoreSignUpTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/OAuthProvider.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/CoreAuthRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/ChangeSocialAccountUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/PhoneVerifyUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/SearchSocialAccountUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/SignInUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/SignUpUseCase.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/Refactor/AuthFeatureBuildable_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/Refactor/SearchSocialAccountPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/Coordinator/AuthBuilder_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/Coordinator/AuthCoordinator_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/PhoneVerifyScene/PhoneVerifyViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/SearchSocialAccountScene/SearchSocialVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/SearchSocialAccountScene/SearchSocialViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/SignInScene/SignInVC_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/SignInScene/SignInViewModel_Refactor.swift
  SOPT-iOS/Projects/Modules/DSKit/Sources/Components/ToolTipView.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/CoreAuthAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/SocialAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/CoreAuth/SocialAccountResultEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/CoreAuthService.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/SocialService.swift
Labels: size/XL

#616 [Refactor] #615 - 인증 중앙화 모듈 분리 및 컨벤션 통일
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Projects/Domain/Sources/Model/OAuthProvider.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/AuthFeatureBuildable_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/ChangeSocialAccountPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/LoginHelpBottomSheetPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/Refactor/SignInPresentable_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/SearchSocialAccountPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/SignInPresentable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/UserNotFoundBuildable.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/ChangeSocialAccountScene/ChangeSocialAccountVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/ChangeSocialAccountScene/ChangeSocialAccountViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/ChangeSocialAccountScene/ChangeSocialOAuthView.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Coordinator/AuthBuilder.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/PhoneVerifyScene/PhoneVerifyView.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/PhoneVerifyScene/PhoneVerifyViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/Coordinator/AuthBuilder_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Refactor/Coordinator/AuthCoordinator_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SearchSocialAccountScene/SearchSocialVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SearchSocialAccountScene/SearchSocialViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/Coordinator/Refactor/AuthCoordiantor_Refactor.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/LoginHelpBottomSheetVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/SignInVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/SignInViewModel.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignInScene/UserNotFoundVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/OAuth/SignUpOAuthView.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/SignUp/SignUpVC.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/SignUpScene/SignUp/SignUpViewModel.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Demo/Resources/Assets.xcassets/Contents.json
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Demo/Resources/LaunchScreen.storyboard
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Demo/Sources/Empty.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Interface/Sources/AuthFeatureBuildable.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Interface/Sources/SignInPresentable.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Project.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/Coordinator/AuthBuilder.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/SignInScene/SignInVC.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/SignInScene/SignInViewModel.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Tests/Resources/Empty.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Tests/Sources/Empty.swift
  SOPT-iOS/Projects/Features/RootFeature/Project.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Tuist/Package.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-iOS/Tuist/Templates/feature/feature.swift
Labels: size/XXL

#628 [Chore] #627 - 테스트앱 로고 변경
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Demo/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.jpg
Labels: size/XS

#638 [Fix] #636 - Splash가 deinit되지 않는 문제 해결
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashCoordinator.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/Coordinator/TabBarCoordinator.swift
Labels: Fix, size/M, 윤서🍉
