Repository sopt-makers/SOPT-iOS, pull requests merged in 2025-09, with the labels that each got.

#694 [Hotfix] tuist fetch -> tuist install로 변경
  SOPT-iOS/fastlane/Fastfile
Labels: size/XS

#695 [Fix] #692 - playgroundid 제거 및 userId로 대체
  SOPT-iOS/Projects/Data/Sources/Transform/PokeUserTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/PokeUserModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/LegacyDailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Interface/Sources/PokeOnboardingPresentable.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Amplitude/PokeEventTracker.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/LegacyPokeCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/LegacyPokeMyFriendsCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/LegacyPokeNotificationListCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeMyFriendsCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/PokeNotificationListCoordinator.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/ViewModel/PokeMainViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMainScene/Views/ProfileCardGroupView.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsListScene/ViewModel/PokeMyFriendsListViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeMyFriendsScene/ViewModel/PokeMyFriendsViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeNotificationScene/ViewModel/PokeNotificationViewModel.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/PokeOnboardingScene/ViewModel/PokeOnboardingViewModel.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/PokeUserEntity.swift
Labels: Fix, size/M, 윤서🍉

#696 [Feat] #673 - 홈화면 앰플리튜드 연동
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeEventPropertyKey.swift
  SOPT-iOS/Projects/Core/Sources/Amplitude/AmplitudeEventType.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomeLatestPostsTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomePopularPostsTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomeLatestPostsModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomePopularPostsModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForMemberPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/Amplitude/HomeAmplitudeEventPropertyValue.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/Amplitude/HomeEventTracker.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/DefaultPost/DefaultPostCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/LegacyHomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/Protocol/PostDisplayable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeLatestPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomePopularPostsResponseEntity.swift
Labels: Feat, size/L, 재현✦

#698 [Chore] #697 - 솝마디에서 콕찌르기 영역 hidden 처리
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
Labels: Chore, size/XS, 재현✦

#705 [chore]#704 - 솦탬프 버튼 텍스트 36기 랭킹에서 개인별 랭킹으로 수정
  SOPT-iOS/Projects/Features/StampFeature/Sources/MissionListScene/VC/MissionListVC.swift
Labels: Chore, size/XS, 현주⚽️
