Repository sopt-makers/SOPT-iOS, pull requests merged in 2025-02, with the labels that each got.

#492 [Feat] #483 - 신규 홈뷰 - DiffableDataSource 적용
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UICollectionView+.swift
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UILabel+.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/HomeUseCase.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Announcements/AnnouncementCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/AppService/AppServiceCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Calendar/CalendarCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/CoffeeChat/CoffeeChatCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/DashBoard/DashBoardCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Group/GroupCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Insight/InsightCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/SocialLinks/SocialLinkCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForMemberCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForVisitorCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForMemberItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForVisitorItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Protocol/HomeSectionKindProtocol.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForVisitorItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/SectionLayoutKind/HomeForMemberSectionLayoutKind.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/SectionLayoutKind/HomeForVisitorSectionLayoutKind.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForVisitorVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForVisitorViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Views/HomeDefaultHeaderView.swift
Labels: Feat, size/XXL, 재현✦

#497 [Setting] #491 - 모듈 생성 자동화 명령어 구현
  SOPT-iOS/Makefile
  SOPT-iOS/Projects/Features/SoptlogFeature/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/Features/SoptlogFeature/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Features/SoptlogFeature/Demo/Resources/Assets.xcassets/Contents.json
  SOPT-iOS/Tuist/Templates/feature/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Tuist/Templates/feature/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Tuist/Templates/feature/Assets.xcassets/Contents.json
  SOPT-iOS/Tuist/Templates/feature/Empty.stencil
  SOPT-iOS/Tuist/Templates/feature/Info.plist
  SOPT-iOS/Tuist/Templates/feature/LaunchScreen.storyboard
  SOPT-iOS/Tuist/Templates/feature/Project.stencil
  SOPT-iOS/Tuist/Templates/feature/feature.swift
Labels: Setting, size/L, 윤서🍉

#494 [Feat] #493 - 신규 홈뷰 - 화면 전환 구현
  SOPT-iOS/Projects/Core/Sources/Extension/UIKit+/UILabel+.swift
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Data/Sources/Repository/HomeRepository.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/HomeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/HomeUseCase.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForMemberPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForVisitorPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Announcements/AnnouncementCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/Calendar/CalendarCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/DashBoard/DashBoardCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/SocialLinks/SocialLinkCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForMemberCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForVisitorCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForMemberItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForVisitorItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForVisitorItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeItemRegistrationTypes.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForVisitorVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForVisitorViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: Feat, size/XL, 재현✦

#500 [Feat] TabBarUI 구현
  SOPT-iOS/Makefile
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Projects/Demo/Sources/Application/SceneDelegate.swift
  SOPT-iOS/Projects/Features/RootFeature/Project.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Interface/Sources/SoptlogPresentable.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/Coordinator/SoptlogCoordinator.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/VC/SoptlogVC.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/ViewModel/SoptlogViewModel.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Demo/Resources/Assets.xcassets/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/Features/TabBarFeature/Demo/Resources/Assets.xcassets/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Features/TabBarFeature/Demo/Resources/Assets.xcassets/Assets.xcassets/Contents.json
  SOPT-iOS/Projects/Features/TabBarFeature/Demo/Resources/LaunchScreen.storyboard
  SOPT-iOS/Projects/Features/TabBarFeature/Demo/Sources/Empty.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Interface/Sources/TabBarBuildable.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Interface/Sources/TabBarPresentable.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Project.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/TabBarBuilder.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/TabBarController.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/TabBarCoordinator.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/TabBarItem.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Sources/TabBarViewModel.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Tests/Resources/Empty.swift
  SOPT-iOS/Projects/Features/TabBarFeature/Tests/Sources/Empty.swift
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/TabBar/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/TabBar/ic_home_filled.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/TabBar/ic_home_filled.imageset/home-filled.svg
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/TabBar/ic_user_filled.imageset/Contents.json
  SOPT-iOS/Projects/Modules/DSKit/Resources/Assets.xcassets/TabBar/ic_user_filled.imageset/user-filled.svg
  SOPT-iOS/Tuist/Templates/feature/feature.swift
Labels: size/XL

#499 [Hotfix] #498 - 신규 홈뷰 및 솝트로그: 두 번째 QA 내용 반영
  SOPT-iOS/Projects/Data/Sources/Transform/SoptlogTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SoptlogModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/VC/DailySoptuneResultVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/CalendarDetailScene/VC/HomeCalendarDetailVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/AppService/AppServiceCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/DashBoard/DashBoardCardCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/DeepLinks/HomeDeepLink.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/Cell/SoptlogAlarmCVC.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/Cell/SoptlogAppServiceCVC.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/VC/SoptlogVC.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/ViewModel/SoptlogViewModel.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/HomeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/SoptlogResponseEntity.swift
Labels: Fix, size/L, 재현✦

#504 [Feat] #502 - 홈뷰, 솝트로그 에러처리 및 푸시알림 권한 요청 플로우 추가
  SOPT-iOS/Projects/Data/Sources/Repository/HomeRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SoptlogRepository.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/HomeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SoptlogRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/HomeUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SoptlogUseCase.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForMemberPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Interface/Sources/SoptlogPresentable.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/Coordinator/SoptlogCoordinator.swift
  SOPT-iOS/Projects/Features/SoptlogFeature/Sources/SoptlogScene/ViewModel/SoptlogViewModel.swift
Labels: Feat, Fix, size/L, 윤서🍉

#505 [Hotfix] #484 - 릴리즈에 배포된 Hotfix/#484 브랜치를 develop에도 머지한다.
  SOPT-iOS/Projects/Core/Sources/Utils/makeAlert.swift
  SOPT-iOS/Projects/Features/WebFeature/Sources/Download/WKDownloadExecutable.swift
  SOPT-iOS/Projects/Features/WebFeature/Sources/Download/WKDownloadManager.swift
  SOPT-iOS/Projects/Features/WebFeature/Sources/Download/WKImageDownloadHandler.swift
  SOPT-iOS/Projects/Features/WebFeature/Sources/SOPTWebView.swift
Labels: size/L
