Repository sopt-makers/SOPT-iOS, pull requests merged in 2025-07, with the labels that each got.

#642 [Refactor] #633 - DailySoptuneFlow의 코디네이터 의존성 제거 방식 변경
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneBuildable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneCardPresentable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneMainPresentable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/DailySoptuneResultPresentable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Interface/Sources/LegacyDailySoptuneFeatureBuildable.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneBuilder.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/DailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/LegacyDailySoptuneBuilder.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/LegacyDailySoptuneCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/Coordinator/LegacyDailySoptuneResultCoordinator.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneMainViewModel.swift
  SOPT-iOS/Projects/Features/DailySoptuneFeature/Sources/DailySoptuneScene/ViewModel/DailySoptuneResultViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
Labels: Refactor, size/L, 윤서🍉

#650 [Refactor] #626 - SplashFlow의 코디네이터 의존성 제거 방식 변경(25.06.19 논의 반영)
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Interface/Sources/LegacySplashFeatureBuildable.swift
  SOPT-iOS/Projects/Features/SplashFeature/Interface/Sources/SplashFeatureBuildable.swift
  SOPT-iOS/Projects/Features/SplashFeature/Interface/Sources/SplashPresentable.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/LegacySplashBuilder.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/LegacySplashCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashBuilder.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/ViewModel/SplashViewModel.swift
Labels: Refactor, size/M, 윤서🍉

#652 [Refactor] #631 - AttendanceFlow의 코디네이터 의존성 제거 방식 변경
  SOPT-iOS/Projects/Features/AttendanceFeature/Interface/Sources/AttendanceFeatureBuildable.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Interface/Sources/LegacyAttendanceFeatureBuildable.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/Coordinator/AttendanceBuilder.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/Coordinator/AttendanceCoordinator.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/Coordinator/LegacyAttendanceBuilder.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/Coordinator/LegacyAttendanceCoordinator.swift
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/ShowAttendanceScene/ViewModel/ShowAttendanceViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
Labels: Refactor, size/M, 윤서🍉

#658 [Del] #653 - NoticeFeature 모듈 제거 및 SplashFinishOutput 프로토콜 추가
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Resources/Assets.xcassets/Contents.json
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Resources/Launch Screen.storyboard
  SOPT-iOS/Projects/Features/NoticeFeature/Demo/Sources/Demo.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Interface/Sources/NoticeFeatureViewControllable.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Project.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Sources/Example.swift
  SOPT-iOS/Projects/Features/NoticeFeature/Tests/Resources/dummy.txt
  SOPT-iOS/Projects/Features/NoticeFeature/Tests/Sources/UnitTest.swift
  SOPT-iOS/Projects/Features/RootFeature/Project.swift
  SOPT-iOS/Projects/Features/SplashFeature/Interface/Sources/SplashPresentable.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashCoordinator.swift
Labels: Del, size/L, 윤서🍉

#647 [Refactor] #569 - RemoteConfig를 활용한 강제 업데이트 구현 (+선택 업데이트 구현)
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  SOPT-iOS/Projects/Core/Sources/Extension/Foundation+/NSBundle+.swift
  SOPT-iOS/Projects/Core/Sources/Firebase/FirebaseService.swift
  SOPT-iOS/Projects/Core/Sources/Firebase/RemoteConfig/RemoteConfigManager.swift
  SOPT-iOS/Projects/Core/Sources/Firebase/RemoteConfig/RemoteConfigType.swift
  SOPT-iOS/Projects/Data/Sources/Repository/SplashRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/AppNoticeTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/ForcedUpdateTransform.swift
  SOPT-iOS/Projects/Demo/Project.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AppNoticeModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/SplashRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/SplashUseCase.swift
  SOPT-iOS/Projects/Features/SplashFeature/Interface/Sources/SplashPresentable.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/LegacySplashCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/Coordinator/SplashCoordinator.swift
  SOPT-iOS/Projects/Features/SplashFeature/Sources/SplashScene/ViewModel/SplashViewModel.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/FirebaseAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/FirebaseService.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Project.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Sources/Empty.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Sources/Example.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Tuist/Package.swift
Labels: Refactor, size/XL, 윤서🍉

#663 [Fix] #662 - AppCoord에 userType 누락된 부분 수정
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
Labels: size/S

#639 [Setting] #421 - Firebase Crashlytics 설정
  SOPT-iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  SOPT-iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  SOPT-iOS/Projects/Core/Sources/Firebase/Crashlytics/CrashlyticsPropertyKeys.swift
  SOPT-iOS/Projects/Core/Sources/Firebase/FirebaseService.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Modules/ThirdPartyLibs/Project.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Tuist/Package.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: size/L

#659 [Fix] #655 - 내부 메서드를 호출하는 딥링크 로직 분기처리
  SOPT-iOS/Projects/Features/AttendanceFeature/Sources/Coordinator/AttendanceModalDeepLink.swift
  SOPT-iOS/Projects/Features/NotificationFeature/Sources/Coordinator/NotificationDetailDeepLink.swift
  SOPT-iOS/Projects/Features/PokeFeature/Sources/Coordinator/DeepLinks/PokeNotificationListDeepLink.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/DeepLinks/SoptampCurrentGenerationRankingDeepLink.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/DeepLinks/SoptampEntireRankingDeepLink.swift
  SOPT-iOS/Projects/Features/StampFeature/Sources/Coordinator/StampCoordinator.swift
Labels: Fix, size/M, 윤서🍉

#672 [Feat] #671 - 홈화면 실시간 인기글, 최신 게시물 API 연동 및 화면 전환 구현
  SOPT-iOS/Projects/Core/Sources/Literals/StringLiterals.swift
  SOPT-iOS/Projects/Data/Sources/Repository/HomeRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomeLatestPostsTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomePlaygroundNewsPostsTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/HomePopularPostsTransform.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomeLatestPostsModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomePlaygroundNewsPostsModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/HomePopularPostsModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/HomeRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/HomeUseCase.swift
  SOPT-iOS/Projects/Features/HomeFeature/Interface/Sources/HomeForMemberPresentable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/DefaultPost/DefaultPostCVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Cells/RecentPost/LatestPostFooterView.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/CompositionalLayout/HomeForMemberCompositionalLayout.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Item/HomeForMemberItem.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeForMemberItemProvider.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/Registration/HomeItemRegistrationTypes.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/CollectionView/SectionLayoutKind/HomeForMemberSectionLayoutKind.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/HomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Coordinator/LegacyHomeCoordinator.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/HomePresentationModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Models/Protocol/PostDisplayable.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/Animation/HomeForMemberAnimationHandler.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/Dummy/DummyPosts.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/VC/HomeForMemberVC.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeForMemberViewModel.swift
  SOPT-iOS/Projects/Features/HomeFeature/Sources/HomeScene/Views/HomeDefaultHeaderView.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/HomeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeLatestPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomePlaygroundNewsPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomePopularPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/CalendarService.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/HomeService.swift
Labels: Feat, size/XL, 재현✦

#667 [Refactor] #665 - on/off 가능한 인증 서버 로직 구축
  SOPT-iOS/Projects/Core/Sources/DIContainer/Injected.swift
  SOPT-iOS/Projects/Core/Sources/FeatureFlag/FeatureFlag.swift
  SOPT-iOS/Projects/Data/Sources/Repository/AuthTokensRepository.swift
  SOPT-iOS/Projects/Data/Sources/Repository/CoreAuthRepository.swift
  SOPT-iOS/Projects/Data/Sources/Transform/CoreLoginTransform.swift
  SOPT-iOS/Projects/Data/Sources/Transform/SignInModelTransform.swift
  SOPT-iOS/Projects/Demo/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Domain/Sources/Model/AuthTokensModel.swift
  SOPT-iOS/Projects/Domain/Sources/Model/CoreAuthTokens.swift
  SOPT-iOS/Projects/Domain/Sources/Model/SignInModel.swift
  SOPT-iOS/Projects/Domain/Sources/RepositoryInterface/CoreAuthRepositoryInterface.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/ChangeSocialAccountUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/SignInUseCase.swift
  SOPT-iOS/Projects/Domain/Sources/UseCase/Auth/SignUpUseCase.swift
  SOPT-iOS/Projects/Features/AuthFeature/Interface/Sources/AuthCoordinatorInterface.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Coordinator/AuthBuilder.swift
  SOPT-iOS/Projects/Features/AuthFeature/Sources/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Coordinator/Options/DeepLinkOptions.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Interface/Sources/AuthFeatureBuildable.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Interface/Sources/SignInPresentable.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Project.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/Coordinator/AuthBuilder.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/Coordinator/AuthCoordinator.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/SignInScene/SignInVC.swift
  SOPT-iOS/Projects/Features/LegacyAuthFeature/Sources/SignInScene/SignInViewModel.swift
  SOPT-iOS/Projects/Features/RootFeature/Sources/ApplicationCoordinator.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/ReissueAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/CoreAuth/CoreSignInEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/ReissueService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Application/AppDelegate.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
Labels: size/L

#675 Fix/#674 - 인증중앙화 적용 시 발생하는 문제를 해결한다.
  SOPT-iOS/Projects/Core/Sources/FeatureFlag/FeatureFlag.swift
  SOPT-iOS/Projects/Core/Sources/Literals/UserDefaultKeyLIst.swift
  SOPT-iOS/Projects/Data/Sources/DI/BaseService+.swift
  SOPT-iOS/Projects/Demo/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Projects/Features/BaseFeatureDependency/Sources/Coordinator/Foundation/CoordinatorFlag.swift
  SOPT-iOS/Projects/Features/WebFeature/Sources/SOPTWebView.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/AttendanceAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/HomeAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/MissionAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/RankAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/ReissueAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/API/StampAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomeLatestPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Entity/ResponseEntity/HomePopularPostsResponseEntity.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Foundation/AccessTokenInterceptor.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Foundation/BaseAPI.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Foundation/BaseService.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Foundation/ReissuanceInterceptor.swift
  SOPT-iOS/Projects/Modules/Networks/Sources/Service/HomeService.swift
  SOPT-iOS/Projects/SOPT-iOS/Sources/Dependency/RegisterDependencies.swift
  SOPT-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: size/L
